name: Call Delete Merged Branches

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  call-delete-merged-branches:
    uses: futbolemotion/.github/.github/workflows/deleted-merged-branches.yml@main