name: Auto Delete Branch on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - pre_prod
      - Qa_test
      - Qa
      - qa
      - QA

jobs:
  delete-branch:
    name: Delete Merged Branch
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Check if branch should be protected
        id: check-protection
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          PROTECTED_BRANCHES="main,pre_prod,Qa_test,Qa,qa,QA"
          
          # Convert to lowercase for case-insensitive comparison
          BRANCH_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')
          PROTECTED_LOWER=$(echo "$PROTECTED_BRANCHES" | tr '[:upper:]' '[:lower:]')
          
          if [[ " $PROTECTED_LOWER " =~ " $BRANCH_LOWER " ]]; then
            echo "protected=true" >> $GITHUB_OUTPUT
            echo "🛡️ Branch '$BRANCH_NAME' is protected and will not be deleted"
          else
            echo "protected=false" >> $GITHUB_OUTPUT
            echo "🗑️ Branch '$BRANCH_NAME' can be deleted"
          fi
      
      - name: Delete merged branch
        if: steps.check-protection.outputs.protected == 'false'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.event.pull_request.head.ref }}
      
      - name: Log protected branch
        if: steps.check-protection.outputs.protected == 'true'
        run: |
          echo "✅ Branch '${{ github.event.pull_request.head.ref }}' is protected and was not deleted"
          echo "Protected branches: main, pre_prod, Qa_test, Qa, qa, QA" 