name: Call Delete Merged Branches

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  call-delete-merged-branches:
    # Solo ejecutar si el PR fue mergeado (no solo cerrado)
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deleted-merged-branches.yml