name: Delete Merged Branches (Reusable)

on:
  workflow_call:
    inputs:
      protected_branches:
        description: 'Comma-separated list of branches to protect from deletion'
        required: false
        default: 'main,pre_prod,Qa_test,Qa,qa,QA'
        type: string
    secrets:
      github_token:
        description: 'GitHub token for repository access'
        required: true

jobs:
  delete-merged-branches:
    name: Delete Merged Branches
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete merged branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.github_token }}
          branches: ${{ inputs.protected_branches }} 