name: Merge main to pre_prod in selected repos

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: "Selecciona los repos que quieres actualizar"
        required: true
        type: choice
        options:
          - futbolemotion/running-zend-src
          - repo-2
          - repo-3
          - repo-4
          - repo-5
          # ... agrega los 38 repos aquí

jobs:
  merge-job:
    name: Merge main → pre_prod
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: |
          echo "REPO_NAME=${{ github.event.inputs.repositories }}" >> $GITHUB_ENV
          echo "CLONE_URL=https://x-access-token:${{ secrets.ORG_REPO_UPDATE_PAT }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.repositories }}.git" >> $GITHUB_ENV

      - name: Clone target repository
        run: |
          git clone --single-branch --branch pre_prod "$CLONE_URL" repo
          cd repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin "$CLONE_URL"
          git fetch origin main

      - name: Merge main into pre_prod
        run: |
          cd repo
          git merge origin/main --no-ff --no-edit || {
            echo "⚠️ Merge conflict detected. Please resolve manually.";
            exit 1;
          }

      - name: Push changes to pre_prod
        run: |
          cd repo
          git push origin pre_prod

