name: Merge main to pre_prod in selected repos

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: "Selecciona el repositorio a actualizar (main → pre_prod)"
        required: true
        type: choice
        options:
          - futbolemotion/running-zend-src
          - repo-2
          - repo-3
          - repo-4
          - repo-5
          # Agrega los 38 repos de tu organización aquí

jobs:
  merge-job:
    name: Merge main → pre_prod
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: |
          echo "REPO_NAME=${{ github.event.inputs.repositories }}" >> $GITHUB_ENV
          echo "CLONE_URL=https://x-access-token:${{ secrets.ORG_REPO_UPDATE_PAT }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.repositories }}.git" >> $GITHUB_ENV

      - name: Check if pre_prod branch exists
        run: |
          BRANCH_EXISTS=$(git ls-remote --heads "$CLONE_URL" pre_prod | wc -l)
          if [ "$BRANCH_EXISTS" -eq 0 ]; then
            echo "❌ La rama 'pre_prod' no existe en el repositorio $REPO_NAME. Saliendo."
            exit 1
          fi

      - name: Clone target repository on pre_prod
        run: |
          git clone --single-branch --branch pre_prod "$CLONE_URL" repo
          cd repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin "$CLONE_URL"
          git fetch origin main

      - name: Merge main into pre_prod
        run: |
          cd repo
          git merge origin/main --no-ff --no-edit || {
            echo "⚠️ Merge conflict detected. Please resolve manually.";
            exit 1;
          }

      - name: Push changes to pre_prod
        run: |
          cd repo
          git push origin pre_prod
